# docker-compose.yml

version: '3.8'
services:

  postgres:
    container_name: postgres_docker_wa
    image: postgres:13.5
    restart: always
    environment:
      - POSTGRES_DB=wedding-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres: