import type {Metadata} from 'next';
import React from "react";
import LandingPageScript from "@/app/components/LandingPageScript";

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
   children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
        <head>
            <title>My wedding</title>
            <meta charSet="utf-8"/>
            <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
            <link href="https://fonts.googleapis.com/css?family=Dosis:300,400,600,700%7COpen+Sans:300,400,700%7CPlayfair+Display:400,400i,700,700i" rel="stylesheet" />
            
            <LandingPageScript />
        </head>
        <body className='gla_middle_titles'>
        {children}
        </body>
        </html>
    )
}
